#!/bin/sh

indent() {
  sed -u 's/^/       /'
}

echo "Install gmplib"

BUILD_DIR=$1
VENDOR_DIR="vendor"
DOWNLOAD_URL="https://gmplib.org/download/gmp/gmp-6.1.0.tar.xz"

echo "DOWNLOAD_URL = " $DOWNLOAD_URL | indent

cd $BUILD_DIR
mkdir $VENDOR_DIR
cd $VENDOR_DIR
curl -L --silent $DOWNLOAD_URL | tar xz
